### ISSUE TITLE
Duplication of `yarn install` across `build` & `dist` steps?

### ISSUE THREAD

**Issue by strogonoff** [paneron/paneron#113]
I was watching current build process and it looks like at least on Windows and macOS `yarn install` happens two separate times, during compile/build and during notarization.

 Is that so? If true, this likely means we have slower builds now than before if we only did `install` once; it’s quite a slow step (as far as we are not on Yarn zero-installs yet).

Some options that I see:

- Unite steps back, if we think that “dist without build” scenario happens sufficiently rarely so that we don’t benefit from caching then we might as well benefit from only installing once
- Separate out the `yarn install` step, cache and share outcome with both `build` and `dist`

cc @ribose-jeffreylau @CAMOBAP

**Comment by ribose-jeffreylau** [comment]
A third option is to use yarn zero-install?

**Comment by ribose-jeffreylau** [comment]
I quite like the second option (_i.e._ to share the `node_modules/`).  It can be done very simply by using `actions/upload-artifact`.  Since `dist` depends on `build` anyway, I think it's OK to keep `yarn install` in `build`.

**Comment by ribose-jeffreylau** [comment]
Uploading `node_modules` as an artifact (using `actions/upload-artifact`) has been tested and it turned out to take more than 4 minutes (yarn install from cold start took less than 2 minutes).  (see: https://github.com/paneron/paneron/actions/runs/6181872111/job/16780564018?pr=114#step:5:7)

Going to test `actions/cache` instead of `actions/upload-artifact`.

**Comment by strogonoff** [comment]
Agreed that using artifacts for this would be an overhead, it may be large and slow even if you zip it into one file…

**Comment by ribose-jeffreylau** [comment]
These two workflow runs ([run 1](https://github.com/paneron/paneron/actions/runs/6182119431), [run 2](https://github.com/paneron/paneron/actions/runs/6182574245/job/16782588154)) have shown that run time of individual build steps can vary a lot.
The first run shows that combining the two steps took 17m32s, while keeping them separate took 12m51s combined, which is contrary to expectation.  The second run (which combined the two steps) took [15m44s](https://github.com/paneron/paneron/actions/runs/6182574245/job/16782588154).

In particular, across the two runs, `yarn dist` took anywhere from [2m20s](https://github.com/paneron/paneron/actions/runs/6182119431/job/16781372581#step:8:1) to [8m45s](https://github.com/paneron/paneron/actions/runs/6182574245/job/16782588154#step:8:1), while `yarn install [opts]` took anywhere from [47s](https://github.com/paneron/paneron/actions/runs/6182119431/job/16781372581#step:4:1) to [1m36s](https://github.com/paneron/paneron/actions/runs/6182119431/job/16781278719#step:4:1).
In a separate run, `yarn dist` even took [15m23s](https://github.com/paneron/paneron/actions/runs/6145986117/job/16674581231#step:8:1).

So, from the limited samples that I have looked into, I think the variance of the time it takes to run `yarn dist` is far greater than that of `yarn install`.

But I'm OK combining `build` and `build-dist` since currently they do belong together logically, and also because when run separately, it typically takes from 37s (=[11s](https://github.com/paneron/paneron/actions/runs/6181947109/job/16780781640#step:12:1) + [26s](https://github.com/paneron/paneron/actions/runs/6181947109/job/16780856923#step:5:1https://github.com/paneron/paneron/actions/runs/6181947109/job/16780856923#step:5:1)) to 57s (=[10s](https://github.com/paneron/paneron/actions/runs/6182119431/job/16781279009#step:12:1) + [47s](https://github.com/paneron/paneron/actions/runs/6182119431/job/16781372581#step:5:1)) to write to and restore from cache.
