### ISSUE TITLE
Support a way to install developmental extensions

### ISSUE THREAD

**Issue by ronaldtse** [paneron/paneron#26]
Often we need to run/debug development extensions that are stored in Git. Copy/pasting code is error prone.

Can we have a way of installing an extension via Git?

**Comment by strogonoff** [comment]
It’s infeasible to do via Git as described, because Git only stores the source, while in order to be usable by Paneron that source needs to be processed and packaged in a certain way, for which we rely on Node environment and libraries not included in Paneron distribution.

We could either (1) allow Paneron to load unpackaged extensions (uncharted area) or (2) have CI for extensions and support for extension release channels (e.g., nightly, beta, stable) in CI, repository workflows, and in Paneron core. I believe the second option will be more preferable, and we’ll have to implement it anyway.

**Comment by strogonoff** [comment]
As a stop-gap measure, a mechanism to load dev-provided extension packages will be implemented in meantime

**Comment by strogonoff** [comment]
A way to add extension packages from local filesystem is added in beta14. Now the user can choose directories containing extension NPM packages in settings. Paneron will use those directories when relevant extensions are installed, even if they have public versions released. Previously implemented confusing command-line flags for dev extension loading were removed.

**Comment by ronaldtse** [comment]
Thanks @strogonoff !

**Comment by strogonoff** [comment]
Correction, this is going into beta15, made a mistake and beta14 was accidentally released too early lacking this change.
