### ISSUE TITLE
Use icon with transparent background

### ISSUE THREAD

**Issue by ronaldtse** [paneron/paneron#54]
The Paneron logo here looks awkward due to its size and lack of transparency around it.

<img width="344" alt="Screen Shot 2022-11-23 at 12 22 32 PM" src="https://user-images.githubusercontent.com/11865/203468792-2de8147b-8f05-4aa9-a397-234158ba4dcf.png">

**Comment by ronaldtse** [comment]
This also affects the Paneron logo inside the app menu bar:
<img width="154" alt="Screen Shot 2022-11-23 at 12 24 54 PM" src="https://user-images.githubusercontent.com/11865/203469004-ac5d062b-51e4-40f9-b221-a8ef62792955.png">

And the application switcher, which I couldn't take a screenshot of.

Right now the size is too large -- I think Apple intentionally allows extra margins around for the notifications number popup.

**Comment by strogonoff** [comment]
Updated icon assets; should be resolved in the upcoming release.

**Comment by strogonoff** [comment]
Previous version: 
<img width="512" alt="icon-1" src="https://user-images.githubusercontent.com/292959/215714051-2b33bd89-6256-4a11-820b-8a097814ee47.png">

Current version:
![icon](https://user-images.githubusercontent.com/292959/215714086-57811372-2cdb-4e7d-9f42-20911255555d.png)

**Comment by strogonoff** [comment]
fixed in 1.0.0-beta26

<img width="69" alt="Screenshot 2023-02-04 at 23 48 52" src="https://user-images.githubusercontent.com/292959/216776817-b288b1ff-c416-450c-a653-640f49d720bc.png">
<img width="236" alt="Screenshot 2023-02-04 at 23 48 36" src="https://user-images.githubusercontent.com/292959/216776824-0a773d83-cd4b-40dd-ae7a-0c7a56cf58ce.png">
