### ISSUE TITLE
Desktop app signing under macOS

### ISSUE THREAD

**Issue by strogonoff** [paneron/paneron#81]
It seems like Paneron build for macOS fails with something about contract… If this costs nothing, we should probably renew (if it does, we should discuss)
cc @ronaldtse @ribose-jeffreylau

**Comment by ronaldtse** [comment]
From Apple Developer Relations

We’re reaching out because you recently used the altool command-line utility to notarize your macOS software with Apple. As announced last year at WWDC22, if you’re still using altool with the Apple notary service, you should transition to the notarytool command-line utility as soon as possible. Notarizing software with altool was deprecated in Xcode 13, and the Apple notary service will no longer accept uploads from altool as of November 1, 2023. Existing notarized software will continue to function properly.For information on notarizing your apps, read TechNote TN3147: Migrating to the latest notarization tool. If you have any questions, contact us. 

But it’s not supposed to rain until November?

**Comment by strogonoff** [comment]
@ronaldtse yeah I’m not quite sure this is what stops the build.

We get two messages, an error and a warning.

```
2023-07-02 04:17:01.501 *** Error: You do not have required contracts to perform an operation. With error code FORBIDDEN_ERROR.CONTRACT_NOT_VALID for id ... You do not have required contracts to perform an operation (-19208)
 {
    NSLocalizedDescription = "You do not have required contracts to perform an operation. With error code FORBIDDEN_ERROR.CONTRACT_NOT_VALID for id ...";
    NSLocalizedFailureReason = "You do not have required contracts to perform an operation";
}
```

```
2023-07-02 04:17:01.502 *** Warning: altool has been deprecated for notarization and starting in late 2023 will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software. (-1030)
```

**Comment by strogonoff** [comment]
It could be that the error is independent from the warning.

**Comment by ronaldtse** [comment]
It looks like the signing account needs to accept a new Apple agreement. I’ll do that and revert.

**Comment by ronaldtse** [comment]
I've just done it and retrying the action:
* https://github.com/paneron/paneron/actions/runs/5434617692

**Comment by ronaldtse** [comment]
It worked! https://github.com/paneron/paneron/actions/runs/5434617692/jobs/9884202657

Closing for now, the new notarization flow should be performed in a new ticket.
